# Generated by Django 3.2.23 on 2024-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.BooleanField(default=False, verbose_name='Назначено'),
        ),
    ]
